# Generated by Django 3.2.6 on 2021-09-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('answer_1', models.CharField(max_length=500)),
                ('answer_2', models.CharField(max_length=500)),
                ('answer_3', models.CharField(max_length=500)),
                ('answer_4', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.course')),
            ],
        ),
    ]
