# Generated by Django 3.2.6 on 2021-09-06 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestApp', '0002_codingquestions_multiplechoicequestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_identification', models.CharField(max_length=10)),
                ('student_pic', models.ImageField(upload_to='static/images/studentimages')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.course')),
            ],
        ),
    ]
